Ref #3218 - Add the LGPL mySQL JDBC driver in studio distribution
Qualif error in trunk come from the unwanted commit of Elodie of the mysql-connector_fake.jar, that cause the !FakeJarException instead of using the true mysql connector from tomcat/lib.

Also add a java version checking before Driver switch to prevent the !NoClassDefFoundError on java.sql.NClob (and just let the !NoClassDefFoundError for com.mysql.jdbc.Driver).

Former-commit-id: 34301938d5d6dd3b29c99932337e2eb2a959c574
Former-commit-id: 10ed7b155309ea1ed56c4c0ecfc0b1215f3f2cdd
Former-commit-id: 55c85b559e7ff3fe58a976e954cf80aeeb494f4a