Ref #3218 - Add the LGPL mySQL JDBC driver in studio distribution
Qualif error in trunk come from the unwanted commit of Elodie of the mysql-connector_fake.jar, that cause the !FakeJarException instead of using the true mysql connector from tomcat/lib.

Also add a java version checking before Driver switch to prevent the !NoClassDefFoundError on java.sql.NClob (and just let the !NoClassDefFoundError for com.mysql.jdbc.Driver).

Former-commit-id: d87decdf831e8330f3e5f4ef7936bedae15e7c06
Former-commit-id: 2eaae3e33a8b53209f2698e4f94c7f77dc94606b
Former-commit-id: 1d0bee4f7da32a7006c66141af6a45ddea8ef55f